server:
    error:
        include-stacktrace: on_param

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/banco
    username: temp
    password: temp
    driver-class-name: org.postgresql.Driver

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    hibernate:
      ddl-auto: update
