package com.WorkFlowManager.project.enums;

public enum PostoGraduacaoAeronautica {
    SOLDADO_2ª_CLASSE,
    TAIFEIRO_2ª_CLASSE,
    SOLDADO_1ª_CLASSE,
    TAIFEIRO_1ª_CLASSE,
    TAIFEIRO_MOR,
    CABO,
    TERCEIRO_SARGENTO,
    SEGUNDO_SARGENTO,
    PRIMEIRO_SARGENTO,
    SUBTOFICIAL,
    ASPIRANTE,
    SEGUNDO_TENENTE,
    PRIMEIRO_TENENTE,
    CAPITÃO,
    MAJOR,
    TENENTE_CORONEL,
    CORONEL,
    BRIGADEIRO,
    MAJOR_BRIGADEIRO,
    TENENTE_BRIGADEIRO_DO_AR,
    MARECHAL_DO_AR
}