package com.WorkFlowManager.project.enums;

public enum PostoGraduacaoExercito {
    SOLDADO,
    TAIFEIRO_SEGUNDA_CLASSE,
    TAIFEIRO_PRIMEIRA_CLASSE,
    TAIFEIRO_MOR,
    CABO,
    TERCEIRO_SARGENTO,
    SEGUNDO_SARGENTO,
    PRIMEIRO_SARGENTO,
    SUBTENENTE,
    ASPIRANTE,
    SEGUNDO_TENENTE,
    PRIMEIRO_TENENTE,
    CAPITÃO,
    MAJOR,
    TENENTE_CORONEL,
    CORONEL,
    GENERAL_DE_BRIGADA,
    GENERAL_DE_DIVISÃO,
    GENERAL_DE_EXÉRCITO,
    MARECHAL
}