package com.WorkFlowManager.project.enums;

public enum Qas {
    ARTILHARIA,
    CAVALARIA,
    COMUNICACOES,
    ENGENHARIA,
    INFANTARIA,
    INTENDÊNCIA,
    MATERIAL_BÉLICO,
    QUADRO_DE_ENGENHEIROS_MILITARES,
    QUADRO_AUXILIAR_DE_OFICIAIS,
    QUADRO_COMPLEMENTAR_DE_OFICIAIS,
    SERVIÇO_DE_ASSITÊNCIA_RELIGIOSA,
    SERVIÇO_DE_SAÚDE
}
